{{- range .Values.workers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
    spec:
      hostNetwork: false
      hostIPC: false
      automountServiceAccountToken: false
      containers:
        - name: worker
          image: {{ .image | quote }}
          imagePullPolicy: "IfNotPresent"
          command: ["/bin/sh", "-c", "{{ .command }}"]
          env:
          {{- if and (eq .name "openrelik-worker-timesketch") $.Values.global.timesketch.enabled }}
            - name: TIMESKETCH_SERVER_URL
              value: {{ printf "http://%s-timesketch:5000" $.Release.Name | quote }}
            - name: TIMESKETCH_USERNAME
              value: timesketch
            - name: TIMESKETCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-timesketch-secret" $.Release.Name | quote }}
                  key: timesketch-user
          {{- else if .env }}
            {{- toYaml .env | nindent 12 }} 
          {{- end }}
          {{- if and (eq .name "openrelik-worker-llm") $.Values.config.analyzers }}
            {{- if $.Values.config.analyzers.llm }}
            {{- if $.Values.config.analyzers.llm.max_input_tokens }}
            - name: LLM_MAX_INPUT_TOKENS
              value: "{{ $.Values.config.analyzers.llm.max_input_tokens }}"
            {{- end }}
            {{- if $.Values.config.analyzers.llm.ollama_server_url }}
            - name: OLLAMA_SERVER_URL
              value: "{{ $.Values.config.analyzers.llm.ollama_server_url }}"
            {{- end }}
            {{- if $.Values.config.analyzers.llm.model }}
            - name: OLLAMA_DEFAULT_MODEL
              value: "{{ $.Values.config.analyzers.llm.model }}"
            {{- end }}
            {{- end }}
          {{- end }}
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                    name: {{ $.Release.Name }}-openrelik-secret 
                    key: redis-url
          volumeMounts:
            - mountPath: /mnt/openrelikvolume
              name: openrelikvolume
            {{- if $.Values.config.analyzers }}
            - name: analyzer-config
              mountPath: /usr/share/openrelik/data
            {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: openrelikvolume
          persistentVolumeClaim:
            {{- if $.Values.persistence.existingPVC }}
            claimName: {{ $.Values.persistence.existingPVC }}
            {{- else }}
            claimName: {{ $.Release.Name }}-openrelikvolume-claim
            {{- end }}
            readOnly: false
        {{- if $.Values.config.analyzers }}
        - name: analyzer-config
          configMap:
            name: {{ $.Release.Name }}-worker-analyzer-config
        {{- end }}
{{- end }}