apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-cache
  namespace: osdfir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: osdfir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          volumeMounts:
            - name: ollama-cache
              mountPath: /root/.ollama
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
              ephemeral-storage: "1Gi"
            limits:
              memory: "4Gi"
              cpu: "2"
              ephemeral-storage: "2Gi"
      volumes:
        - name: ollama-cache
          persistentVolumeClaim:
            claimName: ollama-cache
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: osdfir
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434 