apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: osdfirvolume
  namespace: osdfir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard 